#spring:
#  datasource:
#    url: "jdbc:postgresql://localhost:5433/pdpmigration?currentSchema=sb_flyway"
#    username: postgres
#    password: 123
#    driver-class-name: org.postgresql.Driver
#
#  flyway:
#    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pdpmigration?currentSchema=sb_flyway
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/pdpmigration
    user: postgres
    password: your_password
