server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

products:
  url:
    base: http://localhost:8080/v1/product
    createProduct: ${products.url.base}/create
    updateProduct: ${products.url.base}/update
    deleteProduct: ${products.url.base}/delete
    getProduct: ${products.url.base}/get/{id}
    listProducts: ${products.url.base}/list

logging:
  level:
    org.zalando.logbook: trace
    org:
      springframework:
        web:
          client:
            RestTemplate: trace
