hateoas:
  url:
    base: http://localhost:9088/api/posts/
logging: # request response qatta qanaqaligini korsatadigan log
  level:
    org.zalando.logbook: trace
    org: # restTemplate body sini log lari uchun
      springframework:
        web:
          client:
            RestTemplate: trace
#logbook:
#  predicate:
#    exclude:
#      - /api/posts/comment
##       mana shu uchun log yozma dgani
